fixxed blockchain got new error now
~PS C:\Users\franz\Source\Repos\DuckCoin> node main.js
C:\Users\franz\Source\Repos\DuckCoin\main.js:56
const createGenesisBlock{
      ^^^^^^^^^^^^^^^^^^

SyntaxError: Missing initializer in const d